### ISSUE TITLE
Curtain status

### ISSUE THREAD

**Issue by jonpeng** [OpenWonderLabs/homebridge-switchbot-ble#37] opened 2020-12-26 22:52 UTC
The curtain status won't be updated in HomeKit if the curtain was operated by another APP(such as SwitchBot app, Alexa, etc) or by manually (touch n go).

**Comment by Damianeq90** [comment] 2021-05-04 08:54
Hello,
I have the same problem, if the curtain has changed its position manually (Touch and Go) or in an application other than Home, the status of the curtain is not updated.

**Comment by dnicolson** [comment] 2021-05-30 19:09
This is a duplicate of https://github.com/OpenWonderLabs/homebridge-switchbot-ble/issues/14.

**Closed** 2021-07-14 11:24 UTC
Labels: pinned
