### ISSUE TITLE
Switchbot  - Failed to discover services and characteristics: DISCONNECTED

### ISSUE THREAD

**Issue by daiiig** [OpenWonderLabs/homebridge-switchbot-ble#51] opened 2021-01-08 18:51 UTC
**Describe Your Problem:**
occasionally after the plugin connects to a Switchbot it will generate this error and log instead of changing state.
Error: Failed to discover services and characteristics: DISCONNECTED

I installed the bluetooth abandonware/noble as directed, and it does work most of the time but still get these occasional failures and would like to fix this or at least have a way to give it a retry X times on failure.

**Logs:**

```
[08/01/2021, 02:00:07] [SwitchBotPlatform] Target state of Bot setting: OFF
[08/01/2021, 02:00:10] [SwitchBotPlatform] Scan done.
[08/01/2021, 02:00:10] [SwitchBotPlatform] WoHand (c5:57:f3:94:28:dc) was found.
[08/01/2021, 02:00:10] [SwitchBotPlatform] Bot is running...
[08/01/2021, 02:00:11] [SwitchBotPlatform] Error: Failed to discover services and characteristics: DISCONNECTED
    at SwitchbotDeviceWoHand._ondisconnect_internal (/usr/local/lib/node_modules/@switchbot/homebridge-switchbot-ble/node_modules/node-switchbot/lib/switchbot-device.js:161:16)
    at Peripheral.<anonymous> (/usr/local/lib/node_modules/@switchbot/homebridge-switchbot-ble/node_modules/node-switchbot/lib/switchbot-device.js:122:14)
    at Object.onceWrapper (events.js:421:28)
    at Peripheral.emit (events.js:315:20)
    at Noble.onDisconnect (/usr/local/lib/node_modules/@switchbot/homebridge-switchbot-ble/node_modules/@abandonware/noble/lib/noble.js:224:16)
    at NobleBindings.emit (events.js:315:20)
    at NobleBindings.onDisconnComplete (/usr/local/lib/node_modules/@switchbot/homebridge-switchbot-ble/node_modules/@abandonware/noble/lib/hci-socket/bindings.js:260:10)
    at Hci.emit (events.js:315:20)
    at Hci.onSocketData (/usr/local/lib/node_modules/@switchbot/homebridge-switchbot-ble/node_modules/@abandonware/noble/lib/hci-socket/hci.js:447:12)
    at BluetoothHciSocket.emit (events.js:315:20)
[08/01/2021, 02:00:11] [SwitchBotPlatform] Bot state failed to be set to: OFF
```

**Homebridge Config:**

```
        {
            "devices": [
                {
                    "type": "bot",
                    "name": "mattress.bot",
                    "bleMac": "C5:57:F3:94:28:DC",
                    "scanDuration": 3000
                }
            ],
            "name": "SwitchBotPlatform",
            "platform": "SwitchBotPlatform"
        }

```
Homebridge - v1.1.7
OS-Raspbian GNU/Linux Buster (10)
Node.js Version-v14.15.4
Npm Version-v6.14.9

**Screenshots:**

**Comment by daiiig** [comment] 2021-01-08 19:09
i dont understand why it was auto closed, seems to me i followed the correct format

**Comment by SwitchBot-Wonderlabs** [comment] 2021-01-10 06:17
Duplicate of #52

**Closed by SwitchBot-Wonderlabs** 2021-01-10 06:17 UTC
Labels: pinned, question
